name: Docker Actions
#author: nouranelanzeery1191
description: Dcoker Action
inputs:
  input-1:
    description: "desc"
    required: true
    default: Hello World!
outputs:
  output-1: 
    description: "output"
runs:
  using: "docker"
  image: "Dockerfile"
  args: 
    - ${{ inputs.input-1 }}