# Wokflow name to be displayed in GitHub Actions page
name: GitHubActionsDemo

# GtHub event
on: 
  push
#   branches:
#     - main
#     - feature/123-***
#   branches-ignore:
#     - develop
# pull_request:
#   types: [ closed, labeled ]

# jobs
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: test code
        run: |
           echo "Hello"
           echo "World"
           echo "!"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Files After Checkout
        run: |
          pwd
          ls -al
      - name: using a script
        run: |
          chmod +x ./code/central-scripts/gha.sh
          sh ./code/central-scripts/gha.sh
