  # Wokflow name to be displayed in GitHub Actions page
name: ManualApproval

# GtHub event
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to manually run this workflow on
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - test
          - pre-prod
# jobs
jobs:
  job1:
    environment: 'dev'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microservices: ["svc-1","svc-2"]
    steps:
      - name: test code
        run: |
          echo "hello world!"
  approve:
    runs-on: ubuntu-latest
    needs: [ job1 ]
    environment: pre-prod
    steps:
      - name: Waiting for approval
        run: |
          echo "Waiting for manual approval"