# Wokflow name to be displayed in GitHub Actions page
name: GitHubActionsDemo

# GtHub event
on: 
  push
#   branches:
#     - main
#     - feature
#   branches-ignore:
#     - develop
# pull_request:
#   types: [ closed, labeled ]
#   branches:
#     - main

# jobs
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: test code
        run: |
           echo "Hello"
           echo "World"
           echo "!"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Files After Checkout
        run: |
          pwd
          ls -al
          ls -al $PWD/.github/workflows
      - name: using a script
        run: |
          chmod +x ../../code/central-scripts/gha.sh
          sh ../../code/central-scripts/gha.sh

  # node-version:
  #   strategy: 
  #     matrix: 
  #       os: [macos-latest, ubuntu-latest, windows-latest]
  #       node_version: ["6","8","10"]
  #       include:
  #         - os: ubuntu-latest
  #           node_version: 8
  #           is_ubuntu_8: "true"
  #       exclude:
  #         - os: ubuntu-latest
  #           node_version: 6
  #         - os: macos-latest
  #           node_version: 8
  #     #max-parallel: 2
  #     #fail-fast: true
  #   runs-on: ${{ matrix.os }}
  #   env:
  #     is_ubuntu_8: ${{ matrix.is_ubuntu_8}}
  #   steps:
  #     - name: Log node version
  #       run: node -v
  #     - uses: actions/setup-node@v1
  #       with: 
  #         node-version: ${{ matrix.node_version}}
  #     - name: Log node version After performing a version change
  #       run: node -v
  #     - name: Print Specs
  #       run: |
  #         echo "Current OS version: ${{ matrix.os }}"
  #         echo "Current Node version: ${{ matrix.node_version }}"
  #         echo $is_ubuntu_8
