  # Wokflow name to be displayed in GitHub Actions page
name: MatrixStrategy

# GtHub event
on: push
# jobs
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microservices: ["svc-1","svc-2"]
        env: ["dev","test"]
    steps:
      - name: ${{ matrix.microservices }}.${{ matrix.env }}
        run: |
           echo "${{ matrix.microservices }}" on ${{ matrix.env }}

  
  
