  # Wokflow name to be displayed in GitHub Actions page
name: ManualApproval

# GtHub event
on: push
# jobs
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microservices: ["svc-1","svc-2"]
    steps:
      - name: test code
        run: |
          echo "hello world!"
  approve:
    runs-on: ubuntu-latest
    needs: [ job1 ]
    environment: pre-prod
    steps:
      - name: Waiting for approval
        run: |
          echo "Waiting for manual approval"
